#!/bin/sh

# Copy into .git/hooks/ to add precommit hook

files=`git diff --cached --name-status`
re="src\/.*coffee"
if [[ $files =~ $re ]]
then
  echo "Creating files"
  ./node_modules/coffee-script/bin/coffee -o lib/ -c src/
fi

