// Generated by CoffeeScript 1.6.3
(function() {
  var defineProperty;

  defineProperty = require('./defineProperty');

  defineProperty(Array.prototype, 'toSentence', function() {
    var lastWordConnector, twoWordsConnector, wordsConnector;
    wordsConnector = ", ";
    twoWordsConnector = " and ";
    lastWordConnector = ", and ";
    switch (this.length) {
      case 0:
        return "";
      case 1:
        return this[0];
      case 2:
        return this[0] + twoWordsConnector + this[1];
      default:
        return this.slice(0, -1).join(wordsConnector) + lastWordConnector + this[this.length - 1];
    }
  });

  defineProperty(Array.prototype, 'pluck', function(key) {
    return this.map(function(item) {
      return item != null ? item[key] : void 0;
    });
  });

  defineProperty(Array.prototype, 'findWhere', function(attrs) {
    if (!((attrs != null ? attrs.size() : void 0) > 0)) {
      return;
    }
    return this.find(function(value) {
      var key;
      for (key in attrs) {
        if (attrs[key] !== value[key]) {
          return false;
        }
      }
      return true;
    });
  });

  module.exports = true;

}).call(this);
