// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(target, name, method) {
    return Object.defineProperty(target, name, {
      value: method,
      configurable: true,
      enumerable: false,
      writable: true
    });
  };

}).call(this);
