// Generated by CoffeeScript 1.6.3
(function() {
  var sugar;

  sugar = require('sugar');

  Object.extend();

  require('./object');

  require('./array');

  require('./string');

  module.exports = sugar;

}).call(this);
