// Generated by CoffeeScript 1.6.3
(function() {
  var defineProperty;

  defineProperty = require('./defineProperty');

  defineProperty(Object.prototype, 'mapKeys', function(func) {
    var newObj,
      _this = this;
    newObj = {};
    Object.keys(this).each(function(key) {
      var newKey;
      newKey = func(key);
      return newObj[newKey] = _this[key];
    });
    return newObj;
  });

  module.exports = true;

}).call(this);
